version: '3.8'

services:
  # MariaDB 데이터베이스
  mariadb:
    image: mariadb:10.6
    container_name: superset_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample_dashboard
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset123
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - superset_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Superset 캐싱용)
  redis:
    image: redis:7-alpine
    container_name: superset_redis
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - superset_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Apache Superset
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset_app
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
      - SUPERSET_SECRET_KEY=your_secret_key_here_must_be_at_least_32_bytes_long_for_security
      - SUPERSET_JWT_SECRET=super_secret_jwt_key_that_is_at_least_32_bytes_long_for_async_queries
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://superset:superset123@mariadb:3306/sample_dashboard
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_ENV=development
      - SUPERSET_LOAD_EXAMPLES=no
    ports:
      - "0.0.0.0:8088:8088"
    volumes:
      - ./superset_config.py:/app/superset_config.py
      - superset_data:/app/superset_home
    networks:
      - superset_network
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vue.js Frontend
  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    environment:
      - VUE_APP_SUPERSET_URL=http://localhost:8088
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./vue-frontend:/app
      - /app/node_modules
    networks:
      - superset_network
    depends_on:
      - superset
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  superset_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  superset_data:
    driver: local
  redis_data:
    driver: local